### ISSUE TITLE
Edit company.html 

### ISSUE THREAD

**Issue by PhatCa** [8bitUHM/theta360-automotive-guide#28]
Original Site for Reference:

https://automotive.theta360.guide/pages/ez360.html

Current Stage:

When adding a new data instance to our database, the homepage displays a section with cards representing all companies in the database.

![Screenshot 2024-09-24 at 9 47 11 PM](https://github.com/user-attachments/assets/3ca0eea3-6a5d-4f01-94e8-3800c2f7754e)

Clicking on any of these cards takes the user to a detail page.

![Screenshot 2024-09-24 at 9 49 09 PM](https://github.com/user-attachments/assets/ae8d1812-f68f-40f4-90e5-85458350518a)

Objective:

You will need to modify file company.html located in website/templates/pages/company.html

<img width="316" alt="Screenshot 2024-09-24 at 9 33 45 PM" src="https://github.com/user-attachments/assets/eab78f3d-ba35-4775-bc1a-03242a973aa6">

Our goal is to replicate the layout and features from the [original site](https://automotive.theta360.guide/pages/ez360.html)

![Screenshot 2024-09-24 at 9 16 34 PM](https://github.com/user-attachments/assets/eedb4e0f-39a5-4f0f-9562-407f1846fb6c)

One of the most important features to include is the chart and stat bars.

![Screenshot 2024-09-24 at 9 16 45 PM](https://github.com/user-attachments/assets/bd8ca07c-eb6c-4544-8f1b-6fc1c25c3b73)

You can research available tools for this feature. One tool I found is CanvasJS, but I haven’t tested it for compatibility. Feel free to choose another tool that meets the requirements.

Note:

In our model.py,

There are 2 fields reference_link and reference_link_label. The label will be displayed on the template, and the link will be used in the href attribute.

**Comment by shortxmas** [comment]
closed with #34
